name: Deploy

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: pnpm
      
      - run: pnpm install --frozen-lockfile

      - run: pnpm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: VPS's deployment
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~/apps/porfolio
            git pull --ff-only
            docker compose up -d build
            docker image prune -f